version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    docker:
      - image: cimg/node:20.17.0-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - restore_cache:
          keys:
            - v4-npm-deps-{{ checksum "package-lock.json" }}
            - v4-npm-deps-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v4-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Statically analyzes
          command: npm run mod:eslint
      - run:
          name: Build
          command: npm run prod:build
      - run:
          name: Deploy
          command: node scripts/deploy.js
