version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  build:
    docker:
      - image: cimg/node:16.16.0-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: sudo npm install -g npm@8.11.0
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Statically analyzes
          command: npm run mod:eslint
      - run:
          name: Build
          command: npm run prod:build
      - run:
          name: Deploy
          command: node scripts/deploy.js
