version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Statically analyzes
          command: npm run mod:eslint
      - run:
          name: Build
          command: npm run prod:build
      - run:
          name: Deploy
          command: node scripts/deploy.js
